### ISSUE TITLE
tryJs方式捕获到错误的逻辑会重复执行一次

### ISSUE THREAD

**Issue by biggun1860** [BetterJS/report#10]
tryJs方式捕获到错误的逻辑会重复执行一次，可能导致业务逻辑异常，如重复发起请求等
建议去掉bj-wrap.js模块cat函数的重复try catch逻辑

**Comment by caihuiji** [comment]
已经修复。

![image](https://cloud.githubusercontent.com/assets/2292731/8769245/5e583aec-2ecb-11e5-9151-3a3cb015d636.png)
