### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by haledeng** [BetterJS/report#7]
error.stack 进行 stringify是会有该错误，主要是error.stack某些情况下（或者某些浏览器下）是 [object event] 对象，对该对象进行stringify是会报错。
`该对象的target对象指向了DOM节点，DOM节点本身有循环引用的情况，简单看下ownerDocument这个属性，指向的document对象`

**Comment by caihuiji** [comment]
重复的错误
#4
